name: HealthPal
description: A new Flutter profile project.
publish_to: 'none'
version: 0.1.0+1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.3  # Gunakan versi terbaru
  url_launcher: ^6.3.2       # Gunakan versi terbaru
  http: ^1.6.0              # Gunakan versi terbaru
  mime: ^2.0.0              # Gunakan versi terbaru
  web_socket_channel: ^3.0.3 # Gunakan versi terbaru


environment:
  sdk: ">=3.9.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    # Tambahkan aset jika diperlukan
